# Site settings
title: ZFX5130 Blog 
header-img: "img/post-bg-js-module.jpg"
email: 896235418@qq.com
description: "黄金非宝书为宝. 万事皆空善不空。"
baseurl: ""
url: "http://zfx5130.github.io"
github_username: zfx5130
weibo_username: zfx5130
zhihu_username: zfx5130
csdn_username: zfx5130


# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

rouge: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
  
# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: zfx5130
      header-img: "img/home-bg-o.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : zfx5130
  disqus :
      short_name : zfx5130

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
