# Site settings
title: SmallTiger Blog 
header-img: img/home-bg.jpg
email: 245213009@qq.com
description: "一生只做浪漫极客。@博客主页、个人网站, 知乎／阿里／Front-End／UX Unicorn／Web &amp; Mobile Lover／Motion Design "
baseurl: ""
url: "http://lixiaohu1990.github.io"
twitter_username: lixiaohu
github_username:  lixiaohu1990
facebook_username:  lixiaohu
weibo_username: lixiaohu1990
zhihu_username: lixiaohu

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
