# Site settings
title: ZFX5130 Blog 
header-img: img/home-bg.jpg
email: 896235418@qq.com
description: "黄金非宝书为宝. 万事皆空善不空。"
baseurl: ""
url: "http://zfx5130.github.io"
github_username:  zfx5130
weibo_username: zfx5130
zhihu_username: zfx5130
csdn_username: zfx5130

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
